[versions]
androidGradleVersion = "8.13.2"
appcompatVersion = "1.7.1"
httpclientVersion = "4.5.14"
kotlinVersion = "2.3.21"
legacySupportV4Version = "1.0.0"
lwjglVersion = "2.9.3"
lwjgl_utilVersion = "2.9.3"
[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
httpclient = { module = "org.apache.httpcomponents:httpclient", version.ref = "httpclientVersion" }
legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4Version" }
lwjgl_util = { module = "org.lwjgl.lwjgl:lwjgl_util", version.ref = "lwjgl_utilVersion" }
lwjgl = { module = "org.lwjgl.lwjgl:lwjgl", version.ref = "lwjglVersion" }
[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradleVersion" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
